### ISSUE TITLE
Please provide debiman-auxserver.service in the package

### ISSUE THREAD

**Issue by bdrung** [Debian/debiman#101]
It would be nice if debiman-auxserver.service could be shipped with the package. To make it usable without changing the service file, configuring debiman-auxserver via a configuration file would be nice. Then the service could define:
```
ExecStart=/usr/bin/debiman-auxserver -config /etc/debiman/auxserver.cfg
```
And `/etc/debiman/auxserver.cfg` could look like:
```
base_url=https://manpages.debian.org
index=/srv/man/auxserver.idx
inject_assets=
listen=localhost:2431
```

**Comment by stapelberg** [comment]
I’m not looking to introduce a configuration file at this point.

You can specify command line flags to debiman-auxserver using `systemctl edit`, which will create a drop-in config file in which you can overwrite the `ExecStart` directive.

The package contains debiman-auxserver.service since commit https://anonscm.debian.org/cgit/pkg-go/packages/debiman.git/commit/?id=9d9341eab7e94a59090fc104481680d353590585.

**Comment by bdrung** [comment]
Thanks. I am fine with overwriting the `ExecStart` directive.
