### ISSUE TITLE
for page missing or mislinked

### ISSUE THREAD

**Issue by thedancollins** [Debian/debiman#120]
From main page:  https://wiki.debian.org/ShellCommands
Scroll to "for" highlighted hyperlink shows:  https://manpages.debian.org/man/for.1
Page that comes up https://dyn.manpages.debian.org/man/for.1?

This is happening on Chrome, Firefox and Chrome on Android.  I have not checked other browsers.

**Comment by stapelberg** [comment]
I think the issue is with the wiki page, not with manpages.d.o.

As best as I can tell, the wiki page started out as a listing of shell commands (not just programs, also shell builtins), see [this old revision](https://wiki.debian.org/ShellCommands?action=recall&rev=3). At some point, somebody updated it, added manpage links and removed builtins, but apparently didn’t remove “for”?

There’s no program called “for” as per https://packages.debian.org/search?suite=sid&section=all&arch=any&searchon=contents&keywords=for, and I can’t find a manpage for it in other distributions either.

I think the wiki page is incorrect, and “for” should be removed from there. If you’re looking for your shell’s documentation on “for”, check out e.g. https://manpages.debian.org/testing/zsh-common/zshall.1.en.html#COMPLEX_COMMANDS
