### ISSUE TITLE
The dot after the link is defined as part of the link

### ISSUE THREAD

**Issue by w3lifer** [Debian/debiman#140]
- `osm2pgsql` man page: https://manpages.debian.org/stretch/osm2pgsql/osm2pgsql.1.en.html
- found: http://wiki.openstreetmap.org/wiki/Planet.osm
- not found: [http://wiki.openstreetmap.org/wiki/Planet.osm.](http://wiki.openstreetmap.org/wiki/Planet.osm.)

![image](https://user-images.githubusercontent.com/14075412/163657409-70aa173e-647f-43fe-91c7-4d0d6d436244.png)

**Comment by stapelberg** [comment]
Thanks for the report. This is now fixed. It’ll take a few days before the re-render is complete and fixed pages show up.

Note that the page you linked to is from Debian stretch, whose manpages are no longer updated, so that page remains affected. Only bullseye, testing, unstable and experimental are currently updated. The osm2pgsql manpage has since changed to no longer contain any dots after a URL. Another good page to test is `mysqltest`, though.
