### ISSUE TITLE
jump of pts should use pts(4)

### ISSUE THREAD

**Issue by crpb** [Debian/debiman#178]
Shouldn't it be preferred to use .. how should i put it... core manpages instead of the ones from additional packages?
https://manpages.debian.org/pts -> https://manpages.debian.org/bookworm/openafs-client/pts.1.en.html

At least i would prefer it and i think most users which look for it will likely not thinking about openafs-client's manpage.

**Comment by stapelberg** [comment]
The current search order is determined by the manpage section order: https://github.com/Debian/debiman/blob/4afba3a1fef8fc4215d59c13926082ac1001a987/internal/redirect/redirect.go#L155-L156

This matches the behavior of `man(1)`: When I run `man pts` on a Debian system with openafs-client installed, I see `pts(1)` instead of `pts(4)`.

Your argument seems to be that the `manpages` package should be preferred. That’s a reasonable feature request, but a request for consistency with `man(1)` would be just as reasonable. It’s not clear to me whether diverging from consistency is bottom-line better (because it handles redirects like the `pts` one better) or will just result to a different set of people being confused by the behavior.

**Comment by crpb** [comment]
> with openafs-client installed 
ahh, silly me didn't even think of that.

You are right, that would lead to even more confusion.
I was gonna look at something now but nothing works anymore..dyn.manpages... 
Well, maybe later.

**Comment by stapelberg** [comment]
The debiman-auxserver process wasn’t running anymore on one of the two machines it’s installed on.

Unfortunately, last time I asked, DSA denied my request to set up auxserver as a systemd service with logs and automated restart, so I lack any sort of insight into why the process wasn’t running anymore. I have set up a prober now, so hopefully I will at least be notified should it go down again.
