### ISSUE TITLE
psql (stable) - jumps to chinese translation

### ISSUE THREAD

**Issue by crpb** [Debian/debiman#180]
```
% curl -IL https://manpages.debian.org/bookworm/psql https://manpages.debian.org/stable/psql |grep location
location: https://manpages.debian.org/bookworm/manpages-zh/psql.1.zh_CN.html
location: https://manpages.debian.org/bookworm/manpages-zh/psql.1.zh_CN.html
```
found by @trentbuck

**Comment by stapelberg** [comment]
PostgreSQL is a bit of a special case, see https://github.com/Debian/debiman/issues/12 and https://github.com/Debian/debiman/issues/106 for more background.

The issue here was that the piuparts data file was not correctly updated in the run-debiman.bash script (human mistake when last modifying it, I guess), which is why the redirect index currently does not know about the postgresql-client* packages.

I fixed the issue in the script (wrong filename) and am now the pipeline. It will take a while for the fix to be live, though (likely a day or so).

**Comment by stapelberg** [comment]
This is now fixed:

```
curl -IL https://manpages.debian.org/bookworm/psql https://manpages.debian.org/stable/psql |grep location
location: https://manpages.debian.org/bookworm/postgresql-client-15/psql.1.en.html
content-location: psql.1.en.html.gz
location: https://manpages.debian.org/bookworm/postgresql-client-15/psql.1.en.html
content-location: psql.1.en.html.gz
```
