### ISSUE TITLE
package renames break navigation between different Debian versions

### ISSUE THREAD

**Issue by TobiSGD** [Debian/debiman#27]
Easy to reproduce, either use the search to get to the manpage for systemd-nspawn of Jessie's version and see that you don't find a link to manpages of systemd-nspawn of the Testing and Unstable versions.
Alternatively, browse the manpage repositories of Testing and Unstable to not find the manpages of systemd-nspawn. The same is true for machinectl.
Might this be caused by the move of these tools to a separate package?

**Comment by stapelberg** [comment]
Thanks for the report.

Yes, package renames are not currently tracked. The naive approach of just considering all binary packages when looking for versions in other suites isn’t a good idea either: there are binary packages which contain just translations (e.g. `manpages-de`), and we wouldn’t want to reference these.

Do you have any thoughts as to how a package rename can be programmatically detected in a reliable way? The only thing that comes to my mind is to compare source packages instead of binary packages. This should solve many cases, but possibly not all of them.

**Comment by stapelberg** [comment]
The fix will be live with the next full re-render (next few days).
