### ISSUE TITLE
manpages.debian.org should be a psuedo package for bugs.debian.org

### ISSUE THREAD

**Issue by shirishag75** [Debian/debiman#52]
It would be nice/great if manpages.debian.org was a psuedo package/service like so many which are listed at https://www.debian.org/Bugs/pseudo-packages . It would make it easier to reporter and track down things.

**Comment by stapelberg** [comment]
This is already in progress: https://bugs.debian.org/851885

**Comment by anarcat** [comment]
"in progress"? seems stalled to me. ;) i pinged the issue to try and figure out the next step. in the meantime, i documented the (eventual) pseudo-package in the nascent <a href="https://anonscm.debian.org/git/srv-manpages/debian-assets.git/tree/faq.tmpl?h=faq">FAQ section</a> so that needs review before merging.

**Comment by anarcat** [comment]
"in progress"? seems stalled to me. ;) i pinged the issue to try and figure out the next step. in the meantime, i documented the (eventual) pseudo-package in the nascent <a href="https://anonscm.debian.org/git/srv-manpages/debian-assets.git/tree/faq.tmpl?h=faq">FAQ section</a> so that needs review before merging.

**Comment by anarcat** [comment]
this should also be fixed on the next rebuild.
