### ISSUE TITLE
redirect bpf to bpf.2, not bpf.4freebsd

### ISSUE THREAD

**Issue by anarcat** [Debian/debiman#68]
```
$ curl -s -I https://manpages.debian.org/bpf | grep Location
Location: https://manpages.debian.org/jessie/freebsd-manpages/bpf.4freebsd.en.html
```

What I was looking for is more the Linux kernel bpf manpage:

https://manpages.debian.org/unstable/manpages-dev/bpf.2.en.html

not sure why the freebsd manpages win in this case?

**Comment by stapelberg** [comment]
Thanks for your report!

bpf.4freebsd wins because it’s in jessie, whereas bpf.2 isn’t. Hence, the redirector first filled in the suite to jessie, then had only one choice left to hand out to you.

I’m not sure what we can do here, as this seems like an edge case (which will also solve itself with the next stable release).

If you have any ideas, please feel free to reopen.

**Comment by anarcat** [comment]
On 2017-04-10 23:42:05, Michael Stapelberg wrote:
> Thanks for your report!
>
> bpf.4freebsd wins because it’s in jessie, whereas bpf.2 isn’t. Hence, the redirector first filled in the suite to jessie, then had only one choice left to hand out to you.
>
> I’m not sure what we can do here, as this seems like an edge case (which will also solve itself with the next stable release).
>
> If you have any ideas, please feel free to reopen.

Well, i was actually a little surprised to hit jessie by default. While
I see that it could make sense, I am not sure it's the right
decision. There's this example, but there's also SEO: all those
redirections will keep on changing from release to release, which will
lead to poor SEO.

But maybe I could open a separate issue for this?

**Comment by stapelberg** [comment]
Sure, if you’d like to discuss this, please open a separate issue.

**Comment by anarcat** [comment]
understood, see #69 then
