### ISSUE TITLE
Please allow access to component and source package in the template

### ISSUE THREAD

**Issue by bdrung** [Debian/debiman#88]
I want to change the snapshot.debian.org URL in the manpagefooterextra.tmpl to point to our inhouse repository (directly to the pool subdirectory). To construct the URL, I need access to the component and source package name. Please make them available to the template renderer.

**Comment by stapelberg** [comment]
I just noticed that our links to snapshots.d.o are sometimes broken (e.g. for `mandoc(1)`) because they use the binary package where they should use the source package, so we have an interest in this change, too.

Currently, we drop all data not required for rendering as early as possible, so this change will require quite some plumbing. I hope I can get to it in the next few days.

**Comment by stapelberg** [comment]
This was easier than I originally thought. I also plumbed through the filename, so I’d recommend you just use `{{ .Meta.Package.Filename }}`.

**Comment by bdrung** [comment]
Thanks.
